In [2]:
%matplotlib inline
import torch
import numpy as np

In [1]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(x_data)

NameError: name 'torch' is not defined

In [9]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array,'\n')
print(x_np,'\n')

np.multiply(np_array, 2, out=np_array)
print(np_array,'\n')
print(x_np,'\n')


[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 

[[2 4]
 [6 8]] 

tensor([[2, 4],
        [6, 8]], dtype=torch.int32) 



In [11]:
x_ones = torch.ones_like(x_data)
print(x_ones,'\n')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand,'\n')

tensor([[1, 1],
        [1, 1]]) 

tensor([[0.5967, 0.5600],
        [0.0504, 0.2326]]) 



In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [14]:
tensor = torch.rand(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([0.6268, 0.2532, 0.8246, 0.1498])
First column:  tensor([0.6268, 0.4847, 0.2527, 0.8909])
Last column: tensor([0.1498, 0.4784, 0.2814, 0.1677])
tensor([[0.6268, 0.0000, 0.8246, 0.1498],
        [0.4847, 0.0000, 0.9329, 0.4784],
        [0.2527, 0.0000, 0.5632, 0.2814],
        [0.8909, 0.0000, 0.8913, 0.1677]])


In [17]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[0.6268, 0.0000, 0.8246, 0.1498, 0.6268, 0.0000, 0.8246, 0.1498, 0.6268,
         0.0000, 0.8246, 0.1498],
        [0.4847, 0.0000, 0.9329, 0.4784, 0.4847, 0.0000, 0.9329, 0.4784, 0.4847,
         0.0000, 0.9329, 0.4784],
        [0.2527, 0.0000, 0.5632, 0.2814, 0.2527, 0.0000, 0.5632, 0.2814, 0.2527,
         0.0000, 0.5632, 0.2814],
        [0.8909, 0.0000, 0.8913, 0.1677, 0.8909, 0.0000, 0.8913, 0.1677, 0.8909,
         0.0000, 0.8913, 0.1677]])


In [18]:
# 计算两个张量的矩阵乘法，y1, y2, y3 将具有相同的值
y1 = tensor @ tensor.T  # 使用 @ 符号进行矩阵乘法运算
y2 = tensor.matmul(tensor.T)  # 使用 matmul 方法进行矩阵乘法运算

y3 = torch.rand_like(tensor)  # 创建与给定张量相同大小的随机张量
torch.matmul(tensor, tensor.T, out=y3)  # 将矩阵乘法的结果存储在预先分配的输出张量中


# 计算两个张量的按元素乘积，z1, z2, z3 将具有相同的值
z1 = tensor * tensor  # 使用 * 符号进行按元素乘积运算
z2 = tensor.mul(tensor)  # 使用 mul 方法进行按元素乘积运算

z3 = torch.rand_like(tensor)  # 创建与给定张量相同大小的随机张量
torch.mul(tensor, tensor, out=z3)  # 将按元素乘积的结果存储在预先分配的输出张量中

tensor([[0.3929, 0.0000, 0.6799, 0.0224],
        [0.2350, 0.0000, 0.8703, 0.2288],
        [0.0639, 0.0000, 0.3172, 0.0792],
        [0.7937, 0.0000, 0.7944, 0.0281]])